# Generated by Django 3.1.2 on 2021-04-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_customermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='initialamount',
            new_name='salary',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='expiredate',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='plan',
        ),
    ]
