# Generated by Django 3.1.2 on 2021-04-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trainer',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='unit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='initialamount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
