# Generated by Django 3.1.2 on 2021-04-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_auto_20210418_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
