# Generated by Django 3.1.2 on 2021-04-18 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0012_auto_20210418_2057'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('date', 'name')},
        ),
    ]
